name: learn-github-actions
on:
  push:
    branches: [ our-first-pipeline ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: pwd
      - run: ls -la
