name: dependancy-checker

on: [push]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-alpine
      options: --cpus 1
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2
      - name: Integration test
        run: python factorial.py
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Test which OS the runnner is using
      run: echo "This job is now running on ${{ runner.os }} server hosted by Github!"
    - name: Which branch is checked out
      run: echo "The name of the branch is ${{ github.ref }} in repository ${{ github.repository }}"
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "The ${{ github.repository }} has been cloned to the runner."
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
    - name: Lint with pylint
      run: |
        python lint_test.py

  dependencies-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
      - name: install SNYK CLI
        run: npm install -g snyk
      - name: run Snyk Open Source Test
        run: snyk test
      - name: run Snyk Code Test
        run: snyk code test          